//Hi Karthick. This is working code.
//Add some more functions like when, parallel, etc. Reffere documentation.

pipeline {   
  agent any
  
  triggers {
    pollSCM('*/5 * * * 1-5')
}
  options {
    skipDefaultCheckout(true)
    // Keep the 10 most recent builds.
    buildDiscarder(logRotator(numToKeepStr: '10'))
    timestamps()
}
  environment {
    PATH="/var/lib/jenkins/miniconda3/bin:$PATH"
    registry = "Karthickramasamy007/PROJECTS"
    registryCredentials = "docker_credentials"
    dockerImage = ""
    DOCKERHUB_CREDENTIALS= credentials('dockerhubcredentials')     
    
}

 
  stages {         
    stage("Git Checkout"){           
      steps{                
	   
	      //git credentialsId: 'github', url: 'https://github.com/Karthickramasamy007/demo-cicd-project.git'                 
	      echo 'Git Checkout Completed'
	      sh 'ls'
	      sh 'pwd'
      }        
    }

    stage('Build Docker Image') {         
      steps{                
	      sh 'ls'
	      sh 'pwd'
	      sh 'docker build -t mydockeraccfortest/dockerhubreponame:$BUILD_NUMBER .'           
              echo 'Build Image Completed'                
      }           
    }
    stage('Login to Docker Hub') {         
      steps{                            
	      sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'                 
	      echo 'Login Completed'                
      }           
    }               
    stage('Push Image to Docker Hub') {         
      steps{                            
	      sh 'docker push mydockeraccfortest/dockerhubreponame:$BUILD_NUMBER'                 
              echo 'Push Image Completed'       
      }           
    }      
    stage('Trigger ManifestUpdate') {  //This updates K8's manifies file's docker image with new version ID and that triggers Argo CD.
      steps{
              echo "triggering updatemanifestjob"
              build job: 'updatemanifest', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
      }
            
    }      
  } //stages 
  post{
    always {  
      sh 'docker logout'           
    }
    failure {
        echo "Send e-mail, when failed"
    }      
  } 
}
